/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'RAGIndex': ApiRouteHandler<{ file_path: string; content: string }, unknown, never>
    'RAGContext': ApiRouteHandler<{ query: string; current_file?: string | unknown }, unknown, never>
    'RAGClear': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OllamaModels': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OllamaGenerateEmbedding': ApiRouteHandler<{ text: string }, unknown, never>
    'OllamaCheck': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OllamaChat': ApiRouteHandler<{ model: string; messages: Array<Record<string, string>> }, unknown, never>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FSWriteFile': ApiRouteHandler<{ path: string; content: string }, unknown, never>
    'FSReadFile': ApiRouteHandler<{ path: string }, unknown, never>
    'FSReadDirectory': ApiRouteHandler<{ path: string }, unknown, never>
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: unknown; pet_id: string }, { topic: 'notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'Notification': EventHandler<{ template_id: string; email: string; template_data: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: unknown; foodOrder?: unknown | unknown }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: unknown; pet_id: string } }>
  }
    
}